### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Victor-Morel** [Data-Protection-Control/ADPC#22]
I found a few typos while reading the document:
- [ ] [anonimity](https://www.dataprotectioncontrol.org/spec/#tracking) --> anonymity
- [ ] [enabeling](https://www.dataprotectioncontrol.org/spec/#concept) --> enabling
- [ ] [pretense](https://www.dataprotectioncontrol.org/spec/#misplaced-trust) --> pretence (the former is the American spelling, whereas the rest of the text is in British spelling).

This issue could be used as a typo-tracker BTW.

**Comment by gb-noyb** [comment]
Thanks for finding these!
